<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>wasm</string>
		</array>
		<key>foldingStartMarker</key>
		<string>/\*|^#|^\*|^\b|^\.</string>
		<key>foldingStopMarker</key>
		<string>\*/|^\s*$</string>
		<key>keyEquivalent</key>
		<string>^~S</string>
		<key>name</key>
		<string>WASM</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>match</key>
				<string>![^@$lt;*\t ":()]+\b</string>
				<key>name</key>
				<string>support.function.wasm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?&lt;=@)[^@$&lt;*\t ":]+\b</string>
				<key>name</key>
				<string>keyword.control.operator.wasm</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#quoted-double</string>
			</dict>
			<dict>
				<key>match</key>
				<string>#(m(eta)?|i(ncludes)?|h(andlers)?|c(ode)?|d(ata)?)</string>
				<key>name</key>
				<string>entity.other.attribute-name.section.wasm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\$[\w\d]+</string>
				<key>name</key>
				<string>variable.parameter.wasm</string>
			</dict>
			<dict>
				<key>begin</key>
				<string>/\*</string>
				<key>end</key>
				<string>\*/</string>
				<key>name</key>
				<string>comment.block.wasm</string>
			</dict>
			<dict>
				<key>begin</key>
				<string>//</string>
				<key>end</key>
				<string>$\n?</string>
				<key>name</key>
				<string>comment.line.double-slash.wasm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(-|\+)?\s*[0-9]+(\.[0-9]+)?</string>
				<key>name</key>
				<string>constant.numeric.wasm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>[@&amp;*]</string>
				<key>name</key>
				<string>storage.type.wasm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>:(visited|valid|root|right|required|read-write|read-only|out-range|optional|only-of-type|only-child|nth-of-type|nth-last-of-type|nth-last-child|nth-child|not|link|left|last-of-type|last-child|lang|invalid|indeterminate|in-range|hover|focus|first-of-type|first-line|first-letter|first-child|first|enabled|empty|disabled|default|checked|before|after|active)</string>
				<key>name</key>
				<string>entity.other.attribute-name.tag.pseudo-class</string>
			</dict>
			<dict>
				<key>match</key>
				<string>::(after|before|choices|first-letter|first-line|repeat-index|repeat-item|selection|value)</string>
				<key>name</key>
				<string>entity.other.attribute-name.tag.pseudo-element</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(name|author|orcid|version)\b</string>
				<key>name</key>
				<string>support.type.property-name.wasm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(print|halt)\b</string>
				<key>name</key>
				<string>support.constant.trap.wasm</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
			<key>quoted-single</key>
			<dict>
				<key>begin</key>
				<string>'</string>
				<key>end</key>
				<string>'</string>
				<key>name</key>
				<string>string.quoted.single.wasm</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\\.</string>
						<key>name</key>
						<string>constant.character.escaped.wasm</string>
					</dict>
				</array>
			</dict>
			<key>quoted-double</key>
			<dict>
				<key>begin</key>
				<string>"</string>
				<key>end</key>
				<string>"</string>
				<key>name</key>
				<string>string.quoted.double.wasm</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\\.</string>
						<key>name</key>
						<string>constant.character.escaped.wasm</string>
					</dict>
				</array>
			</dict>
			<key>nested-parens</key>
			<dict>
				<key>begin</key>
				<string>\(</string>
				<key>captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.scope.wasm</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\)</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#nested-parens</string>
					</dict>
				</array>
			</dict>
		</dict>
		<key>scopeName</key>
		<string>source.wasm</string>
		<key>uuid</key>
		<string>CD532E06-2406-45BE-8306-CC6BA68EB3B4</string>
	</dict>
</plist>
